apiVersion: apps/v1
kind: Deployment
metadata:
  name: taller-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taller-backend
  template:
    metadata:
      labels:
        app: taller-backend
    spec:
      containers:
        - name: taller-backend
          image: adrianojeda/taller-backend:v10
          ports:
            - containerPort: 8080  # Update to match the actual backend port
---
apiVersion: v1
kind: Service
metadata:
  name: taller-backend-service
spec:
  selector:
    app: taller-backend
  ports:
    - protocol: TCP
      port: 8080       # Service port
      targetPort: 8080 # Container port the backend listens on
      nodePort: 30080  # The external port to access the backend
  type: NodePort  # Expose the service using NodePort
